language: php

php:
  - 5.6
  - 7.0

install:
  - composer install --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always

script:
  -  cp ./.env.example ./.env
  -  touch ./database/lumtify.sqlite
  -  php artisan migrate --seed
  -  php artisan jwt:secret
  -  vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 24a6843f-ce8c-4f1c-bb89-ccc8de9eced1
